import type { CityInfo, PensionItem, StayHistoryItem, UniversityInfo } from './types';

export const MOCK_CITIES: CityInfo[] = [
  {
    id: 'santiago',
    name: 'Santiago',
    region: 'Región Metropolitana',
    foreignStudentRate: 0.64,
    pensionsCount: 38,
    averagePriceClp: 285000,
    imageUrl:
      'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?auto=format&fit=crop&w=800&q=80',
    isCurrentCity: true,
    latitude: -33.4489,
    longitude: -70.6693,
  },
  {
    id: 'valparaiso',
    name: 'Valparaíso',
    region: 'Región de Valparaíso',
    foreignStudentRate: 0.72,
    pensionsCount: 24,
    averagePriceClp: 245000,
    imageUrl:
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80',
    latitude: -33.0472,
    longitude: -71.6127,
  },
  {
    id: 'concepcion',
    name: 'Concepción',
    region: 'Región del Biobío',
    foreignStudentRate: 0.69,
    pensionsCount: 29,
    averagePriceClp: 230000,
    imageUrl:
      'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=800&q=80',
    latitude: -36.8201,
    longitude: -73.0444,
  },
  {
    id: 'valdivia',
    name: 'Valdivia',
    region: 'Región de Los Ríos',
    foreignStudentRate: 0.58,
    pensionsCount: 16,
    averagePriceClp: 260000,
    imageUrl:
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    latitude: -39.8142,
    longitude: -73.2459,
  },
  {
    id: 'temuco',
    name: 'Temuco',
    region: 'Región de La Araucanía',
    foreignStudentRate: 0.52,
    pensionsCount: 14,
    averagePriceClp: 215000,
    imageUrl:
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    latitude: -38.7359,
    longitude: -72.5904,
  },
  {
    id: 'antofagasta',
    name: 'Antofagasta',
    region: 'Región de Antofagasta',
    foreignStudentRate: 0.49,
    pensionsCount: 12,
    averagePriceClp: 310000,
    imageUrl:
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    latitude: -23.6509,
    longitude: -70.3975,
  },
];

export const MOCK_UNIVERSITIES: UniversityInfo[] = [
  {
    id: 'uchile',
    name: 'Universidad de Chile',
    acronym: 'UCHILE',
    city: 'Santiago',
    domains: ['uchile.cl', 'ingenieria.uchile.cl', 'med.uchile.cl'],
    foreignStudentRate: 0.74,
    pensionsNearbyCount: 22,
    imageUrl:
      'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=80',
    latitude: -33.4442,
    longitude: -70.6517,
  },
  {
    id: 'puc',
    name: 'Pontificia Universidad Católica de Chile',
    acronym: 'UC',
    city: 'Santiago',
    domains: ['uc.cl'],
    foreignStudentRate: 0.71,
    pensionsNearbyCount: 19,
    imageUrl:
      'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    latitude: -33.4975,
    longitude: -70.6128,
  },
  {
    id: 'udec',
    name: 'Universidad de Concepción',
    acronym: 'UdeC',
    city: 'Concepción',
    domains: ['udec.cl'],
    foreignStudentRate: 0.68,
    pensionsNearbyCount: 18,
    imageUrl:
      'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80',
    latitude: -36.8298,
    longitude: -73.0378,
  },
  {
    id: 'uv',
    name: 'Universidad de Valparaíso',
    acronym: 'UV',
    city: 'Valparaíso',
    domains: ['uv.cl', 'alumnos.uv.cl'],
    foreignStudentRate: 0.65,
    pensionsNearbyCount: 15,
    imageUrl:
      'https://images.unsplash.com/photo-1592280771190-3e2e4d571952?auto=format&fit=crop&w=800&q=80',
    latitude: -33.0233,
    longitude: -71.5518,
  },
  {
    id: 'utfsm',
    name: 'Universidad Técnica Federico Santa María',
    acronym: 'USM',
    city: 'Valparaíso',
    domains: ['sansano.usm.cl', 'usm.cl'],
    foreignStudentRate: 0.63,
    pensionsNearbyCount: 14,
    imageUrl:
      'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=800&q=80',
    latitude: -33.0353,
    longitude: -71.5947,
  },
  {
    id: 'uach',
    name: 'Universidad Austral de Chile',
    acronym: 'UACh',
    city: 'Valdivia',
    domains: ['uach.cl', 'alumnos.uach.cl'],
    foreignStudentRate: 0.59,
    pensionsNearbyCount: 11,
    imageUrl:
      'https://images.unsplash.com/photo-1576495199011-eb94736d05d6?auto=format&fit=crop&w=800&q=80',
    latitude: -39.8055,
    longitude: -73.2536,
  },
];

export const MOCK_PENSIONS: PensionItem[] = [
  {
    id: 'pen-1',
    slug: 'residencia-universitaria-rep-santiago',
    title: 'Residencia República Estudiantil',
    description:
      'Pensión universitaria acogedora a pasos del Barrio Universitario. Ambiente de estudio tranquilo, cocina compartida totalmente equipada y WiFi de alta velocidad.',
    address: 'Av. República 345',
    neighborhood: 'Barrio Universitario',
    city: 'Santiago',
    latitude: -33.4512,
    longitude: -70.6668,
    priceMonthlyClp: 279600,
    depositClp: 140000,
    ratingAverage: 4.8,
    reviewsCount: 23,
    isVerified: true,
    genderPreference: 'MIXED',
    includesMeals: false,
    includesWifi: true,
    includesLaundry: true,
    includesStudyRoom: true,
    nearestUniversityName: 'Universidad de Chile (Campus Beauchef)',
    distanceToUniversityMeters: 450,
    curfewDescription: 'Acceso autónomo con tarjeta magnética 24/7',
    visitsPolicy: 'Visitas permitidas en áreas comunes hasta las 22:00 hrs',
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
    ],
    rooms: [
      {
        id: 'room-1-1',
        title: 'Pieza Individual con Baño Privado',
        roomType: 'SINGLE',
        priceMonthlyClp: 279600,
        hasPrivateBathroom: true,
        isAvailable: true,
        photos: [
          'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
        ],
      },
      {
        id: 'room-1-2',
        title: 'Pieza Individual con Baño Compartido',
        roomType: 'SINGLE',
        priceMonthlyClp: 235000,
        hasPrivateBathroom: false,
        isAvailable: true,
        photos: [
          'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
  },
  {
    id: 'pen-2',
    slug: 'casa-estudiante-san-joaquin',
    title: 'Hogar Estudiantil Campus San Joaquín',
    description:
      'Pensión familiar con pensión completa (desayuno y almuerzo) pensada para alumnos de regiones. Cercana a metro San Joaquín y Campus UC.',
    address: 'Vicuña Mackenna 4890',
    neighborhood: 'San Joaquín',
    city: 'Santiago',
    latitude: -33.4982,
    longitude: -70.6135,
    priceMonthlyClp: 268177,
    depositClp: 130000,
    ratingAverage: 4.9,
    reviewsCount: 31,
    isVerified: true,
    genderPreference: 'MIXED',
    includesMeals: true,
    includesWifi: true,
    includesLaundry: true,
    includesStudyRoom: true,
    nearestUniversityName: 'Pontificia Universidad Católica (San Joaquín)',
    distanceToUniversityMeters: 300,
    curfewDescription: 'Portón cerrado a las 00:00 dom-jue, flexible fines de semana',
    visitsPolicy: 'Visitas familiares previa coordinación',
    photos: [
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80',
    ],
    rooms: [
      {
        id: 'room-2-1',
        title: 'Habitación Luminosa Norte',
        roomType: 'SINGLE',
        priceMonthlyClp: 268177,
        hasPrivateBathroom: false,
        isAvailable: true,
        photos: [
          'https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
  },
  {
    id: 'pen-3',
    slug: 'residencia-bellavista-providencia',
    title: 'Pensión Bellavista & Providencia',
    description:
      'Excelente conectividad, sector seguro con áreas verdes y vida cultural. Habitaciones amobladas con escritorio amplio y luz natural.',
    address: 'Pio Nono 240',
    neighborhood: 'Providencia / Bellavista',
    city: 'Santiago',
    latitude: -33.4354,
    longitude: -70.6345,
    priceMonthlyClp: 327000,
    depositClp: 160000,
    ratingAverage: 4.7,
    reviewsCount: 18,
    isVerified: true,
    genderPreference: 'MIXED',
    includesMeals: false,
    includesWifi: true,
    includesLaundry: true,
    includesStudyRoom: false,
    nearestUniversityName: 'Universidad de Chile (Facultad de Derecho)',
    distanceToUniversityMeters: 200,
    curfewDescription: 'Llave propia 24/7 sin toque de queda',
    visitsPolicy: 'Permitidas hasta medianoche',
    photos: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80',
    ],
    rooms: [
      {
        id: 'room-3-1',
        title: 'Habitación Ejecutiva Estudiante',
        roomType: 'SINGLE',
        priceMonthlyClp: 327000,
        hasPrivateBathroom: true,
        isAvailable: true,
        photos: [
          'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
  },
  {
    id: 'pen-4',
    slug: 'pension-universitaria-toesca',
    title: 'Residencia Toesca Universitaria',
    description:
      'Ambiente enfocado 100% en estudiantes foráneos. Espacios comunes amplios, sala de estudio insonorizada y cocina común.',
    address: 'Toesca 1920',
    neighborhood: 'Santiago Centro',
    city: 'Santiago',
    latitude: -33.4548,
    longitude: -70.6631,
    priceMonthlyClp: 235327,
    depositClp: 115000,
    ratingAverage: 4.6,
    reviewsCount: 14,
    isVerified: true,
    genderPreference: 'MIXED',
    includesMeals: false,
    includesWifi: true,
    includesLaundry: true,
    includesStudyRoom: true,
    nearestUniversityName: 'Universidad Diego Portales / U. Central',
    distanceToUniversityMeters: 380,
    curfewDescription: 'Ingreso digital con clave personal',
    visitsPolicy: 'Solo visitas diurnas de estudio',
    photos: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80',
    ],
    rooms: [
      {
        id: 'room-4-1',
        title: 'Habitación Individual Económica',
        roomType: 'SINGLE',
        priceMonthlyClp: 235327,
        hasPrivateBathroom: false,
        isAvailable: true,
        photos: [
          'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
  },
  {
    id: 'pen-5',
    slug: 'hogar-estudiantes-playa-ancha-valpo',
    title: 'Hogar Playa Ancha Marina',
    description:
      'Vista privilegiada a la bahía, sector universitario tradicional de Valparaíso. Casa patrimonial remodelada para estudiantes con calefacción.',
    address: 'Av. Gran Bretaña 1120',
    neighborhood: 'Playa Ancha',
    city: 'Valparaíso',
    latitude: -33.0289,
    longitude: -71.6385,
    priceMonthlyClp: 247500,
    depositClp: 120000,
    ratingAverage: 4.9,
    reviewsCount: 27,
    isVerified: true,
    genderPreference: 'MIXED',
    includesMeals: true,
    includesWifi: true,
    includesLaundry: true,
    includesStudyRoom: true,
    nearestUniversityName: 'Universidad de Valparaíso (Campus Playa Ancha)',
    distanceToUniversityMeters: 250,
    curfewDescription: 'Horario libre para estudiantes con llave',
    visitsPolicy: 'Salas de estudio habilitadas para grupos',
    photos: [
      'https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=80',
    ],
    rooms: [
      {
        id: 'room-5-1',
        title: 'Habitación Vista Mar',
        roomType: 'SINGLE',
        priceMonthlyClp: 247500,
        hasPrivateBathroom: true,
        isAvailable: true,
        photos: [
          'https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
  },
  {
    id: 'pen-6',
    slug: 'residencia-plaza-peru-concepcion',
    title: 'Residencia Plaza Perú Universitaria',
    description:
      'Ubicación inmejorable en el corazón del Barrio Universitario de Concepción. Salón de lectura, servicio de aseo y pensión completa opcional.',
    address: 'Plaza Perú 124',
    neighborhood: 'Barrio Universitario',
    city: 'Concepción',
    latitude: -36.8285,
    longitude: -73.0412,
    priceMonthlyClp: 295865,
    depositClp: 145000,
    ratingAverage: 4.9,
    reviewsCount: 39,
    isVerified: true,
    genderPreference: 'MIXED',
    includesMeals: true,
    includesWifi: true,
    includesLaundry: true,
    includesStudyRoom: true,
    nearestUniversityName: 'Universidad de Concepción (Arco UdeC)',
    distanceToUniversityMeters: 120,
    curfewDescription: 'Recepción 24 horas',
    visitsPolicy: 'Visitas permitidas en terraza y lobby',
    photos: [
      'https://images.unsplash.com/photo-1560448204-61dc36dc98c8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    ],
    rooms: [
      {
        id: 'room-6-1',
        title: 'Habitación Premium Frente a Campus',
        roomType: 'SINGLE',
        priceMonthlyClp: 295865,
        hasPrivateBathroom: true,
        isAvailable: true,
        photos: [
          'https://images.unsplash.com/photo-1560448204-61dc36dc98c8?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
  },
  {
    id: 'pen-7',
    slug: 'pension-estudiantil-isla-teja-valdivia',
    title: 'Pensión Los Alerces Isla Teja',
    description:
      'Rodeada de naturaleza en Isla Teja, a 5 minutos a pie de la UACh. Calefacción central, ambiente muy amigable para estudiantes del sur.',
    address: 'Los Laureles 45',
    neighborhood: 'Isla Teja',
    city: 'Valdivia',
    latitude: -39.8082,
    longitude: -73.2505,
    priceMonthlyClp: 183150,
    depositClp: 90000,
    ratingAverage: 4.8,
    reviewsCount: 16,
    isVerified: true,
    genderPreference: 'MIXED',
    includesMeals: false,
    includesWifi: true,
    includesLaundry: true,
    includesStudyRoom: true,
    nearestUniversityName: 'Universidad Austral de Chile (Campus Isla Teja)',
    distanceToUniversityMeters: 280,
    curfewDescription: 'Entrada autónoma',
    visitsPolicy: 'Ambiente de estudio y descanso',
    photos: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    ],
    rooms: [
      {
        id: 'room-7-1',
        title: 'Habitación Teja Verde',
        roomType: 'SINGLE',
        priceMonthlyClp: 183150,
        hasPrivateBathroom: false,
        isAvailable: true,
        photos: [
          'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=80',
        ],
      },
    ],
  },
];

export const MOCK_STAY_HISTORY: StayHistoryItem[] = [
  {
    id: 'stay-1',
    pensionId: 'pen-1',
    pensionTitle: 'Residencia República Estudiantil',
    pensionCity: 'Santiago',
    roomTitle: 'Pieza Individual con Baño Privado',
    startDate: '2025-03-01',
    endDate: '2025-12-20',
    ratingGiven: 5,
    hasReview: true,
    monthlyPaidClp: 279600,
    imageUrl:
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'stay-2',
    pensionId: 'pen-4',
    pensionTitle: 'Residencia Toesca Universitaria',
    pensionCity: 'Santiago',
    roomTitle: 'Habitación Individual Económica',
    startDate: '2024-03-01',
    endDate: '2024-12-15',
    ratingGiven: 4,
    hasReview: true,
    monthlyPaidClp: 235327,
    imageUrl:
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
  },
];
